spring.application.name=public_transportation_project

# חשוב: אומר ל-Spring ליצור את הטבלאות מה-Java לפני שהוא מריץ את ה-data.sql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# מאפשר ל-SQL לרוץ בכל פעם שהאפליקציה עולה
spring.sql.init.mode=always

# הגדרות H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect